### PR TITLE
Fix record button height

### PR DESCRIPTION
**Pull request by MariyaShavshy**
On some devices the record button was very distorted, I've made the font smaller and the buttons wider.
Will of course merge it only after merging #30 and #31, I need to make those slight design changes as I'm taking UI screenshots for the report
FYI, this is how it used to look on my end:
beforeRecordFixed

### CODE REVIEW

**Comment by itoogii** [comment]
Oh I see. Thank you so much.

**Review by agamm — COMMENTED** [review]
What about using media queries?

**Comment by MariyaShavshy** [comment]
I don't have enough time to do media queries properly, if you guys want to implement it - please do :)
This is the last day I am able to work on the project... so please approve my merges and then feel free to take the wheel to any direction you'd like ;)
I'll check in tomorrow to see if everything is approved, otherwise - please take care of that on your end as I won't be available on the 12th (I'll be on a very long flight)

**Review by agamm — APPROVED** [review]
💯

**Pull request merged**
